### ISSUE TITLE
Extension of the client with the SDK from Anybrain

### ISSUE THREAD

**Issue by makando95** [playt-net/client#66]
**Intro**

The SDK was successfully implemented in our test game "Rolling Rick". Now we need to extend this to the real games.

Follow-Up of https://github.com/playt-net/fun-fair/issues/591

**Acceptance criteria**

- The client has been extended with the Anybrain SDK. All games are now always automatically connected to Anybrain and transmit data 
- First analytics can be viewed via the Anybrain dashboard

**Comment by makando95** [comment]
**BLOCKER**

Unfortunately, we have to rely on another change in Anybrain SDK. There is a major security issue that the player ID can be manipulated in the client. This would result in players who hack being able to assign their data to another player and we would consequently ban the wrong player.

**Comment by makando95** [comment]
**Blocker solved:** 

We will provide an endpoint where anybrain can retrieve both the matchId and userId based on a playerToken

**Comment by jeysal** [comment]
Has not been worked on for two days since I was busy with #892.
Current status:
* Waiting for a new Anybrain SDK.
* Experience for dev studios (users of the PLAYT browser client) must be improved, we cannot force them to adapt their webpack config just to be able to load the PLAYT browser client

**Comment by jeysal** [comment]
Relevant PRs: https://github.com/playt-net/rolling-rick/pull/39 https://github.com/playt-net/client/pull/68

**Comment by jeysal** [comment]
https://github.com/playt-net/anybrain-sdk created for an Anybrain SDK distribution with our patches that will be depended on by https://github.com/playt-net/client
We need to:
* Clarify with Anybrain if they agree with us publishing a version of their Anybrain SDK to NPM and what license it is (But I see no reason why not, because we would be hosting it on a web server either way, which is not much different to publishing on NPM)
* Add build steps to anybrain-sdk to change the distribution into a shape that can be imported without custom webpack config (e.g. WASM inlining)
* Receive the new SDK version from Anybrain
* And we still have various TODOs in client and rolling-rick regarding the browser/server client split

**Comment by jeysal** [comment]
Open PRs (higher up depends on lower down):

* https://github.com/playt-net/fun-fair/pull/972
* https://github.com/playt-net/rolling-rick/pull/39
* https://github.com/playt-net/client/pull/68
* https://github.com/playt-net/anybrain-sdk/pull/1

**Comment by jeysal** [comment]
Alright, all done! We are waiting for Anybrain's approval to ship our new PLAYT client SDK version with their Anybrain SDK included to NPM and tell our game devs to update to the new version.

Once approval is there we should, in this order:
* Merge https://github.com/playt-net/anybrain-sdk/pull/1 (this can be done prior to the approval)
* Publish `@playt/anybrain-sdk@1.0.0` (this is blocked by their approval and thus blocks everything below)
* Merge https://github.com/playt-net/client/pull/68 (might need package-lock updates)
* Publish `@playt/client@5.0.0`
* Merge https://github.com/playt-net/rolling-rick/pull/39 (might need package-lock updates)
* Merge https://github.com/playt-net/fun-fair/pull/972

Follow ups for this ticket are:
* #999
* #1000

**Comment by jeysal** [comment]
TODOs:

* For some reason, it only works locally and not when deployed
* We should change the client to not require putting in an anybrain key, but instead request the anybrain key from the game. This will allow easily configuring dev and prod with different anybrain keys as well

**Comment by jeysal** [comment]
See above comment for what is missing.
I paused this because https://github.com/playt-net/fun-fair/issues/861 disturbs our workflow more at the moment

**Comment by jeysal** [comment]
Action plan:
1. Ship https://github.com/playt-net/fun-fair/pull/1033 (has some failing tests that need to be looked into, and needs review/discussion)
2. Create Anybrain game keys/secrets for the games in the database (for dev / Rolling Rick use Anybrain Test Data switch)
3. Ship https://github.com/playt-net/client/pull/69 (nice)
4. Release `@playt/client@6` and update the following Rolling Rick PR to it
5. Ship https://github.com/playt-net/rolling-rick/pull/41
6. Check that Anybrain works for Rolling Rick
7. Ask Flying Sheep to update to `@playt/client@6`
8. ???
9. Profit

**Comment by jeysal** [comment]
Works...more than before.
Current problems:
* CORS headers on `/match/[id]` not present as they should be
* match 404s (probably permissions issue?)

**Comment by jeysal** [comment]
Should be all fixed. Waiting for Anybrain to respond / allow CORS.

**Comment by jeysal** [comment]
It works! Just played this Rolling Rick match on staging https://dashboard.anybrain.gg/games/rolling-rick/matches/match/63fe3c220e335b04ffd37a96?livemode=false
